
name: Release

on:
  push:
    tags:
      - "v*"   
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build release artifacts
        run: make release

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: build/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
